#!/usr/bin/env node

/**
 * autotrade-bridge.js
 * HyperVibe <-> autotrade integration bridge
 *
 * Usage:
 *   node autotrade-bridge.js run   --coin SOL --timeframe 1h --iterations 20
 *   node autotrade-bridge.js parse --results ./autotrade/src/results.jsonl --coin SOL
 *   node autotrade-bridge.js export --results ./autotrade/src/results.jsonl --coin SOL --out ./playbooks/signals/
 *
 * Requires:
 *   - autotrade cloned at ./autotrade (or --autotrade-dir path)
 *   - Claude Code CLI installed globally: npm install -g @anthropic-ai/claude-code
 */

import fs from "fs";
import path from "path";
import { execSync, spawn } from "child_process";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ─── Constants ────────────────────────────────────────────────────────────────

const HL_MAX_CANDLES = 5000;

const CANDLES_PER_TIMEFRAME = {
  "1m": 60 * 24 * 3,         //  ~3 days
  "5m": 12 * 24 * 17,        // ~17 days
  "15m": 4 * 24 * 52,        // ~52 days
  "1h": 24 * 208,            // ~208 days
  "4h": 6 * 833,             // ~833 days (limited to HL max)
  "1d": 5000,                // ~13 years (limited to HL max)
};

const EXCHANGE_ID = "hyperliquid";
const MARKET_TYPE = "swap";

// ─── Helpers ──────────────────────────────────────────────────────────────────

function log(msg, level = "info") {
  const prefix = {
    info:  "[\x1b[36mINFO\x1b[0m]",
    ok:    "[\x1b[32m OK \x1b[0m]",
    warn:  "[\x1b[33mWARN\x1b[0m]",
    error: "[\x1b[31mERR \x1b[0m]",
    step:  "[\x1b[35mSTEP\x1b[0m]",
  }[level];
  console.log(`${prefix} ${msg}`);
}

function parseArgs(argv) {
  const args = { _: [] };
  for (let i = 2; i < argv.length; i++) {
    if (argv[i].startsWith("--")) {
      const key = argv[i].slice(2).replace(/-([a-z])/g, (_, c) => c.toUpperCase());
      args[key] = argv[i + 1]?.startsWith("--") || !argv[i + 1] ? true : argv[++i];
    } else {
      args._.push(argv[i]);
    }
  }
  return args;
}

function autoStartDate(timeframe) {
  const minutesPerCandle = {
    "1m": 1, "5m": 5, "15m": 15, "1h": 60, "4h": 240, "1d": 1440,
  };
  const minutes = (minutesPerCandle[timeframe] || 60) * HL_MAX_CANDLES;
  const ms = minutes * 60 * 1000;
  const date = new Date(Date.now() - ms);
  return date.toISOString().split("T")[0];
}

function coinToSymbol(coin) {
  return `${coin.toUpperCase()}/USDC:USDC`;
}

function compositeScore(m) {
  // Weighted composite: profit factor, Sharpe, drawdown penalty
  const sharpe = m.sharpe_ratio ?? 0;
  const dd = Math.abs(m.max_drawdown_pct ?? 0);
  return (m.profit_factor ?? 0) * (1 + Math.max(sharpe, 0)) * (1 - dd / 100);
}

// ─── Step 1: Generate .env ────────────────────────────────────────────────────

export function generateEnv(params, autotradeDir) {
  const {
    coin = "HYPE",
    timeframe = "1h",
    start_date = "auto",
    total_cash = 10000,
    max_drawdown_limit = -25,
    min_profit_factor = 1.2,
    max_leverage = 3,
  } = params;

  const symbol = coinToSymbol(coin);
  const startDate = start_date === "auto" ? autoStartDate(timeframe) : start_date;

  const env = [
    `# Generated by autotrade-bridge.js — ${new Date().toISOString()}`,
    `TOTAL_CASH=${total_cash}`,
    `MARKET_TYPE=${MARKET_TYPE}`,
    `EXCHANGE_ID=${EXCHANGE_ID}`,
    `SYMBOL=${symbol}`,
    `START_DATE=${startDate}`,
    `END_DATE=`,
    `MAX_DRAWDOWN_LIMIT=${max_drawdown_limit}`,
    `MIN_PROFIT_FACTOR=${min_profit_factor}`,
    `MAX_LEVERAGE=${max_leverage}`,
    `TIMEFRAME=${timeframe}`,
  ].join("\n");

  const envPath = path.join(autotradeDir, ".env");
  fs.writeFileSync(envPath, env + "\n");

  log(`Generated .env for ${symbol} @ ${timeframe}`, "ok");
  log(`  Start date : ${startDate}`, "info");
  log(`  Max DD     : ${max_drawdown_limit}%`, "info");
  log(`  Min PF     : ${min_profit_factor}`, "info");

  return { envPath, symbol, startDate };
}

// ─── Step 2: Run autotrade ────────────────────────────────────────────────────

export function runAutotrade(params, autotradeDir) {
  const {
    iterations = 20,
    llm = "claude",
    coin = "HYPE",
  } = params;

  const maxTurns = iterations * 3; // ~3 Claude turns per strategy experiment
  const logFile = path.join(autotradeDir, `autotrade_${coin}_${Date.now()}.log`);

  const commands = {
    claude: [
      "claude",
      "-p", `Read src/program.md and run ${iterations} strategy experiments on ${coin} perpetuals. Focus on trend-following and momentum strategies suitable for crypto perps.`,
      "--dangerously-skip-permissions",
      "--max-turns", String(maxTurns),
    ],
    codex: [
      "codex", "exec",
      `Read src/program.md and run ${iterations} strategy experiments.`,
      "--full-auto",
    ],
    gemini: [
      "gemini",
      "-p", `Read src/program.md and run ${iterations} strategy experiments.`,
      "--sandbox", "none",
    ],
  };

  const cmd = commands[llm];
  if (!cmd) throw new Error(`Unknown LLM: ${llm}. Use claude | codex | gemini`);

  log(`Launching autotrade with ${llm} CLI (${iterations} iterations)`, "step");
  log(`Logging to: ${logFile}`, "info");

  const logStream = fs.createWriteStream(logFile, { flags: "a" });

  return new Promise((resolve, reject) => {
    const child = spawn(cmd[0], cmd.slice(1), {
      cwd: autotradeDir,
      stdio: ["ignore", "pipe", "pipe"],
    });

    child.stdout.on("data", (d) => {
      process.stdout.write(d);
      logStream.write(d);
    });
    child.stderr.on("data", (d) => {
      process.stderr.write(d);
      logStream.write(d);
    });
    child.on("close", (code) => {
      logStream.end();
      if (code === 0 || code === null) {
        log("autotrade run completed", "ok");
        resolve({ logFile });
      } else {
        log(`autotrade exited with code ${code}`, "warn");
        resolve({ logFile, exitCode: code }); // resolve anyway — partial results are ok
      }
    });
    child.on("error", reject);
  });
}

// ─── Step 3: Parse results.jsonl ─────────────────────────────────────────────

export function parseResults(resultsPath, filterParams = {}) {
  const {
    min_profit_factor = 1.0,
    max_drawdown_limit = -30,
    coin = null,
  } = filterParams;

  if (!fs.existsSync(resultsPath)) {
    throw new Error(`results.jsonl not found at: ${resultsPath}`);
  }

  const raw = fs.readFileSync(resultsPath, "utf-8");
  const lines = raw.split("\n").filter((l) => l.trim());

  log(`Found ${lines.length} experiment(s) in results.jsonl`, "info");

  const experiments = lines.map((line, i) => {
    try {
      return JSON.parse(line);
    } catch {
      log(`Skipping malformed line ${i + 1}`, "warn");
      return null;
    }
  }).filter(Boolean);

  // Normalize metric keys — autotrade may use various naming conventions
  const normalized = experiments.map((exp) => {
    const m = exp.metrics ?? exp.result ?? exp;
    return {
      strategy_file: exp.strategy_file ?? exp.file ?? exp.name ?? "unknown",
      iteration: exp.iteration ?? exp.run ?? null,
      coin: exp.coin ?? exp.symbol ?? coin ?? "unknown",
      timeframe: exp.timeframe ?? "unknown",
      backtest_metrics: {
        total_return_pct: m.total_return ?? m.return_pct ?? m.total_return_pct ?? 0,
        profit_factor: m.profit_factor ?? m.pf ?? 0,
        max_drawdown_pct: m.max_drawdown ?? m.max_dd ?? m.max_drawdown_pct ?? 0,
        sharpe_ratio: m.sharpe ?? m.sharpe_ratio ?? 0,
        num_trades: m.num_trades ?? m.trades ?? 0,
        win_rate_pct: m.win_rate ?? m.win_rate_pct ?? 0,
      },
      raw_params: exp.params ?? exp.strategy_params ?? {},
    };
  });

  // Filter by thresholds
  const valid = normalized.filter((e) => {
    const m = e.backtest_metrics;
    return (
      m.profit_factor >= min_profit_factor &&
      m.max_drawdown_pct >= max_drawdown_limit // drawdown is negative, so >= means less bad
    );
  });

  log(`Valid strategies (PF >= ${min_profit_factor}, DD >= ${max_drawdown_limit}%): ${valid.length}/${normalized.length}`, "info");

  if (valid.length === 0) {
    log("No strategies passed filters. Try relaxing min_profit_factor or max_drawdown_limit.", "warn");
    // Return the best available anyway as a fallback, marked as not ready
    const fallback = [...normalized].sort(
      (a, b) => compositeScore(b.backtest_metrics) - compositeScore(a.backtest_metrics)
    );
    return { valid: [], best: fallback[0] ?? null, all: normalized };
  }

  // Score and rank
  const ranked = valid.sort(
    (a, b) => compositeScore(b.backtest_metrics) - compositeScore(a.backtest_metrics)
  );

  const best = ranked[0];
  log(`Best strategy: ${best.strategy_file}`, "ok");
  log(`  Return    : ${best.backtest_metrics.total_return_pct.toFixed(2)}%`, "info");
  log(`  PF        : ${best.backtest_metrics.profit_factor.toFixed(3)}`, "info");
  log(`  Max DD    : ${best.backtest_metrics.max_drawdown_pct.toFixed(2)}%`, "info");
  log(`  Sharpe    : ${best.backtest_metrics.sharpe_ratio.toFixed(3)}`, "info");
  log(`  Win rate  : ${best.backtest_metrics.win_rate_pct.toFixed(1)}%`, "info");
  log(`  Trades    : ${best.backtest_metrics.num_trades}`, "info");

  return { valid: ranked, best, all: normalized };
}

// ─── Step 4: Export HyperVibe signal config ───────────────────────────────────

export function exportSignal(parseResult, params, outDir) {
  const { best, valid } = parseResult;
  const {
    coin = "HYPE",
    timeframe = "1h",
    max_leverage = 3,
    min_profit_factor = 1.0,
    max_drawdown_limit = -30,
  } = params;

  if (!best) {
    log("Cannot export: no valid strategy found.", "error");
    return null;
  }

  const m = best.backtest_metrics;
  const isReadyForLive =
    m.profit_factor >= min_profit_factor &&
    m.max_drawdown_pct >= max_drawdown_limit &&
    m.num_trades >= 10; // minimum statistical significance

  // Extract risk params from raw strategy or derive safe defaults
  const rawParams = best.raw_params ?? {};
  const stopLoss = rawParams.stop_loss_pct ?? rawParams.sl ?? Math.abs(m.max_drawdown_pct / (m.num_trades || 10));
  const takeProfit = rawParams.take_profit_pct ?? rawParams.tp ?? stopLoss * (m.profit_factor || 1.5);
  const positionSize = rawParams.position_size_pct ?? rawParams.size ?? 20; // default 20% of capital

  const signal = {
    playbook_id: "strategy-research",
    coin: coin.toUpperCase(),
    symbol: coinToSymbol(coin),
    timeframe,
    strategy_file: best.strategy_file,
    backtest_metrics: m,
    composite_score: parseFloat(compositeScore(m).toFixed(4)),
    signal_params: {
      entry_conditions: rawParams.entry ?? rawParams.entry_conditions ?? {
        note: "Extract from strategy file manually — see strategy_file path.",
      },
      exit_conditions: rawParams.exit ?? rawParams.exit_conditions ?? {
        note: "Extract from strategy file manually — see strategy_file path.",
      },
      risk: {
        max_leverage: Math.min(rawParams.leverage ?? max_leverage, max_leverage),
        stop_loss_pct: parseFloat(Math.abs(stopLoss).toFixed(2)),
        take_profit_pct: parseFloat(Math.abs(takeProfit).toFixed(2)),
        position_size_pct: parseFloat(positionSize),
      },
    },
    alternatives: valid.slice(1, 4).map((e) => ({
      strategy_file: e.strategy_file,
      composite_score: parseFloat(compositeScore(e.backtest_metrics).toFixed(4)),
      profit_factor: e.backtest_metrics.profit_factor,
      max_drawdown_pct: e.backtest_metrics.max_drawdown_pct,
    })),
    generated_at: new Date().toISOString(),
    ready_for_live: isReadyForLive,
    warnings: [
      !isReadyForLive ? "Strategy did not pass all readiness checks. Review before live deployment." : null,
      m.num_trades < 30 ? `Low trade count (${m.num_trades}) — limited statistical significance.` : null,
      Math.abs(m.max_drawdown_pct) > 20 ? `Drawdown ${m.max_drawdown_pct}% is high. Consider reducing leverage.` : null,
    ].filter(Boolean),
  };

  // Write output
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

  const filename = `signal_${coin.toLowerCase()}_${timeframe}_${Date.now()}.json`;
  const outPath = path.join(outDir, filename);
  fs.writeFileSync(outPath, JSON.stringify(signal, null, 2));

  log(`Signal exported: ${outPath}`, "ok");
  log(`Ready for live: ${isReadyForLive ? "\x1b[32mYES\x1b[0m" : "\x1b[33mNO — review first\x1b[0m"}`, isReadyForLive ? "ok" : "warn");

  if (signal.warnings.length > 0) {
    signal.warnings.forEach((w) => log(w, "warn"));
  }

  return { signal, outPath };
}

// ─── CLI entrypoint ───────────────────────────────────────────────────────────

async function main() {
  const args = parseArgs(process.argv);
  const command = args._[0];

  const autotradeDir = args.autotradeDir ?? path.join(__dirname, "autotrade");
  const resultsPath  = args.results ?? path.join(autotradeDir, "src", "results.jsonl");
  const outDir       = args.out ?? path.join(__dirname, "playbooks", "signals");

  const params = {
    coin:               args.coin        ?? "HYPE",
    timeframe:          args.timeframe   ?? "1h",
    start_date:         args.startDate   ?? "auto",
    total_cash:         Number(args.totalCash ?? 10000),
    max_drawdown_limit: Number(args.maxDrawdown ?? -25),
    min_profit_factor:  Number(args.minPf ?? 1.2),
    max_leverage:       Number(args.maxLeverage ?? 3),
    iterations:         Number(args.iterations ?? 20),
    llm:                args.llm         ?? "claude",
  };

  log(`autotrade-bridge.js — HyperVibe strategy research pipeline`, "info");
  log(`Command: ${command ?? "(none)"}`, "info");

  switch (command) {
    case "run": {
      // Full pipeline: generate env → run autotrade → parse → export
      generateEnv(params, autotradeDir);
      await runAutotrade(params, autotradeDir);
      const parseResult = parseResults(resultsPath, params);
      exportSignal(parseResult, params, outDir);
      break;
    }

    case "parse": {
      const parseResult = parseResults(resultsPath, params);
      console.log(JSON.stringify(parseResult.best, null, 2));
      break;
    }

    case "export": {
      const parseResult = parseResults(resultsPath, params);
      const result = exportSignal(parseResult, params, outDir);
      if (result) log(`Done: ${result.outPath}`, "ok");
      break;
    }

    case "env": {
      // Just generate the .env without running anything
      const { envPath } = generateEnv(params, autotradeDir);
      log(`Written: ${envPath}`, "ok");
      break;
    }

    default: {
      console.log(`
Usage: node autotrade-bridge.js <command> [options]

Commands:
  run     Full pipeline (env → autotrade → parse → export)
  env     Only generate .env for autotrade
  parse   Parse an existing results.jsonl and print best strategy
  export  Parse results.jsonl and write HyperVibe signal JSON

Options:
  --coin           <string>   Hyperliquid coin ticker (default: HYPE)
  --timeframe      <string>   Candle timeframe: 15m | 1h | 4h | 1d (default: 1h)
  --start-date     <string>   Backtest start YYYY-MM-DD or 'auto' (default: auto)
  --total-cash     <number>   Simulated capital USDC (default: 10000)
  --max-drawdown   <number>   Max drawdown limit % negative (default: -25)
  --min-pf         <number>   Minimum profit factor (default: 1.2)
  --max-leverage   <number>   Max leverage (default: 3)
  --iterations     <number>   LLM strategy iterations (default: 20)
  --llm            <string>   LLM CLI: claude | codex | gemini (default: claude)
  --autotrade-dir  <path>     Path to autotrade clone (default: ./autotrade)
  --results        <path>     Path to results.jsonl (default: ./autotrade/src/results.jsonl)
  --out            <path>     Output directory for signal JSONs (default: ./playbooks/signals/)

Examples:
  node autotrade-bridge.js run --coin SOL --timeframe 1h --iterations 30
  node autotrade-bridge.js run --coin BTC --timeframe 4h --max-leverage 2 --min-pf 1.5
  node autotrade-bridge.js parse --coin ETH --results ./autotrade/src/results.jsonl
  node autotrade-bridge.js export --coin HYPE --out ./playbooks/signals/
      `);
    }
  }
}

main().catch((err) => {
  log(err.message, "error");
  process.exit(1);
});
